import type { Component } from 'svelte';
import {
	Utensils,
	UtensilsCrossed,
	ShoppingCart,
	Car,
	Home,
	Coffee,
	Plane,
	Heart,
	Gift,
	Smartphone,
	Book,
	Music,
	Film,
	Wallet,
	CreditCard,
	Banknote,
	PiggyBank,
	Briefcase,
	GraduationCap,
	Dumbbell,
	Pill,
	Fuel,
	ShoppingBag,
	Bus,
	Train,
	Bike,
	Tag,
	Receipt,
	Wifi,
	Tv,
	Shirt,
	Baby,
	PawPrint,
	Hammer,
	Sparkles,
	Zap,
	Lightbulb,
	Droplet,
	Flame,
	Wrench,
	Stethoscope,
	HeartPulse,
	Bed,
	Bath,
	Sofa,
	Refrigerator,
	WashingMachine,
	Trash2,
	TreePine,
	Cigarette,
	Beer,
	Pizza,
	IceCream,
	Cake,
	Apple,
	Salad,
	Beef,
	Wine,
	Soup,
	GlassWater,
	Cookie,
	Camera,
	Headphones,
	Gamepad2,
	Tickets,
	Newspaper,
	Palette,
	Scissors,
	Brush,
	Glasses,
	Watch,
	Diamond,
	Crown,
	Backpack,
	Luggage,
	BedDouble,
	MapPin,
	Compass,
	Mountain,
	Tent,
	Anchor,
	Ship,
	HandCoins,
	Landmark,
	Building2,
	BadgeDollarSign,
	TrendingUp,
	TrendingDown,
	HandHeart,
	HelpingHand,
	Church,
	Star,
	Bookmark,
	Award
} from 'lucide-svelte';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type IconComponent = Component<any> | (new (...args: any[]) => any);

export const CATEGORY_ICONS: { name: string; label: string; icon: IconComponent }[] = [
	// Food & drink
	{ name: 'utensils', label: 'Food', icon: Utensils },
	{ name: 'utensils-crossed', label: 'Restaurant', icon: UtensilsCrossed },
	{ name: 'coffee', label: 'Coffee', icon: Coffee },
	{ name: 'pizza', label: 'Pizza', icon: Pizza },
	{ name: 'soup', label: 'Soup', icon: Soup },
	{ name: 'beef', label: 'Meat', icon: Beef },
	{ name: 'salad', label: 'Salad', icon: Salad },
	{ name: 'apple', label: 'Fruit', icon: Apple },
	{ name: 'cake', label: 'Cake', icon: Cake },
	{ name: 'cookie', label: 'Snack', icon: Cookie },
	{ name: 'ice-cream', label: 'Ice cream', icon: IceCream },
	{ name: 'beer', label: 'Beer', icon: Beer },
	{ name: 'wine', label: 'Wine', icon: Wine },
	{ name: 'glass-water', label: 'Drinks', icon: GlassWater },
	// Shopping & lifestyle
	{ name: 'shopping-cart', label: 'Groceries', icon: ShoppingCart },
	{ name: 'shopping-bag', label: 'Shopping', icon: ShoppingBag },
	{ name: 'shirt', label: 'Clothing', icon: Shirt },
	{ name: 'glasses', label: 'Glasses', icon: Glasses },
	{ name: 'watch', label: 'Watch', icon: Watch },
	{ name: 'diamond', label: 'Jewelry', icon: Diamond },
	{ name: 'crown', label: 'Luxury', icon: Crown },
	{ name: 'gift', label: 'Gifts', icon: Gift },
	// Home & utilities
	{ name: 'home', label: 'Home', icon: Home },
	{ name: 'bed', label: 'Bedroom', icon: Bed },
	{ name: 'bed-double', label: 'Hotel', icon: BedDouble },
	{ name: 'bath', label: 'Bath', icon: Bath },
	{ name: 'sofa', label: 'Furniture', icon: Sofa },
	{ name: 'refrigerator', label: 'Appliance', icon: Refrigerator },
	{ name: 'washing-machine', label: 'Laundry', icon: WashingMachine },
	{ name: 'zap', label: 'Listrik', icon: Zap },
	{ name: 'lightbulb', label: 'Light', icon: Lightbulb },
	{ name: 'droplet', label: 'Air', icon: Droplet },
	{ name: 'flame', label: 'Gas', icon: Flame },
	{ name: 'wrench', label: 'Utilities', icon: Wrench },
	{ name: 'hammer', label: 'Repair', icon: Hammer },
	{ name: 'trash', label: 'Trash', icon: Trash2 },
	{ name: 'tree-pine', label: 'Garden', icon: TreePine },
	// Tech & subscription
	{ name: 'wifi', label: 'Internet', icon: Wifi },
	{ name: 'tv', label: 'Subscriptions', icon: Tv },
	{ name: 'smartphone', label: 'Phone', icon: Smartphone },
	{ name: 'headphones', label: 'Audio', icon: Headphones },
	{ name: 'gamepad-2', label: 'Gaming', icon: Gamepad2 },
	{ name: 'camera', label: 'Camera', icon: Camera },
	// Transport & travel
	{ name: 'car', label: 'Car', icon: Car },
	{ name: 'fuel', label: 'Fuel', icon: Fuel },
	{ name: 'bus', label: 'Bus', icon: Bus },
	{ name: 'train', label: 'Train', icon: Train },
	{ name: 'bike', label: 'Bike', icon: Bike },
	{ name: 'plane', label: 'Flight', icon: Plane },
	{ name: 'ship', label: 'Ship', icon: Ship },
	{ name: 'anchor', label: 'Marine', icon: Anchor },
	{ name: 'luggage', label: 'Luggage', icon: Luggage },
	{ name: 'backpack', label: 'Backpack', icon: Backpack },
	{ name: 'tent', label: 'Camping', icon: Tent },
	{ name: 'mountain', label: 'Outdoor', icon: Mountain },
	{ name: 'compass', label: 'Travel', icon: Compass },
	{ name: 'map-pin', label: 'Location', icon: MapPin },
	// Health & care
	{ name: 'heart', label: 'Health', icon: Heart },
	{ name: 'heart-pulse', label: 'Medical', icon: HeartPulse },
	{ name: 'stethoscope', label: 'Doctor', icon: Stethoscope },
	{ name: 'pill', label: 'Pharmacy', icon: Pill },
	{ name: 'dumbbell', label: 'Fitness', icon: Dumbbell },
	{ name: 'baby', label: 'Kids', icon: Baby },
	{ name: 'paw-print', label: 'Pets', icon: PawPrint },
	{ name: 'cigarette', label: 'Tobacco', icon: Cigarette },
	// Education & entertainment
	{ name: 'book', label: 'Education', icon: Book },
	{ name: 'graduation-cap', label: 'School', icon: GraduationCap },
	{ name: 'music', label: 'Music', icon: Music },
	{ name: 'film', label: 'Movies', icon: Film },
	{ name: 'tickets', label: 'Tickets', icon: Tickets },
	{ name: 'newspaper', label: 'News', icon: Newspaper },
	{ name: 'palette', label: 'Art', icon: Palette },
	{ name: 'brush', label: 'Beauty', icon: Brush },
	{ name: 'scissors', label: 'Salon', icon: Scissors },
	{ name: 'sparkles', label: 'Personal', icon: Sparkles },
	// Money & work
	{ name: 'banknote', label: 'Cash', icon: Banknote },
	{ name: 'wallet', label: 'Wallet', icon: Wallet },
	{ name: 'credit-card', label: 'Card', icon: CreditCard },
	{ name: 'piggy-bank', label: 'Savings', icon: PiggyBank },
	{ name: 'hand-coins', label: 'Income', icon: HandCoins },
	{ name: 'badge-dollar-sign', label: 'Salary', icon: BadgeDollarSign },
	{ name: 'trending-up', label: 'Investment', icon: TrendingUp },
	{ name: 'trending-down', label: 'Loss', icon: TrendingDown },
	{ name: 'briefcase', label: 'Work', icon: Briefcase },
	{ name: 'building-2', label: 'Office', icon: Building2 },
	{ name: 'landmark', label: 'Bank', icon: Landmark },
	{ name: 'receipt', label: 'Bills', icon: Receipt },
	// Misc
	{ name: 'hand-heart', label: 'Charity', icon: HandHeart },
	{ name: 'helping-hand', label: 'Help', icon: HelpingHand },
	{ name: 'church', label: 'Religion', icon: Church },
	{ name: 'star', label: 'Star', icon: Star },
	{ name: 'bookmark', label: 'Bookmark', icon: Bookmark },
	{ name: 'award', label: 'Award', icon: Award },
	{ name: 'tag', label: 'Other', icon: Tag }
];

export function getIconByName(name: string | null | undefined): IconComponent | null {
	if (!name) return null;
	return CATEGORY_ICONS.find((i) => i.name === name)?.icon ?? null;
}
